---
# namespaces are tidy
apiVersion:                    v1
kind:                          Namespace
metadata:
  name:                        registry
---
# persistent storage is probably a good move
apiVersion:                    v1
kind:                          PersistentVolumeClaim
metadata:
  name:                        registry-pvc
  namespace:                   registry
spec:
  storageClassName:            rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:                 25Gi
---
# TODO:                        do we care about tls?
apiVersion:                    apps/v1
kind:                          Deployment
metadata:
  name:                        registry
  namespace:                   registry
spec:
  replicas:                    1
  selector:
    matchLabels:
      app:                     registry
  template:
    metadata:
      labels:
        app:                   registry
    spec:
      containers:
      - name:                  registry
        image:                 registry:2
        ports:
        - name:                registry-port
          containerPort:       5000
        volumeMounts:
        - name:                registry-storage
          mountPath:           /var/lib/registry
      volumes:
      - name:                  registry-storage
        persistentVolumeClaim:
          claimName:           registry-pvc
---
apiVersion:                    v1
kind:                          Service
metadata:
  name:                        registry
  namespace:                   registry
spec:
  type:                        LoadBalancer
  loadBalancerIP:              192.168.1.129
  selector:
    app:                       registry
  ports:
  - port:                      5000
    targetPort:                5000
    name:                      registry-port
